// Mocks generated by Mockito 5.4.6 from annotations
// in dia_app/test/core/mocks/mocks_generator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dia_app/core/utils/result.dart' as _i4;
import 'package:dia_app/features/login/domain/repo_interfaces/auth_repo_interface.dart'
    as _i2;
import 'package:dia_app/features/tasks/domain/entities/item.dart' as _i8;
import 'package:dia_app/features/tasks/domain/repo_interfaces/task_repo_interface.dart'
    as _i7;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepoInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoInterface extends _i1.Mock implements _i2.AuthRepoInterface {
  @override
  _i3.Future<_i4.Result<_i5.User?>> loginWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
              _i6.dummyValue<_i4.Result<_i5.User?>>(
                this,
                Invocation.method(#loginWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User?>>.value(
              _i6.dummyValue<_i4.Result<_i5.User?>>(
                this,
                Invocation.method(#loginWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<dynamic>> deleteCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentUser, []),
            returnValue: _i3.Future<_i4.Result<dynamic>>.value(
              _i6.dummyValue<_i4.Result<dynamic>>(
                this,
                Invocation.method(#deleteCurrentUser, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<dynamic>>.value(
              _i6.dummyValue<_i4.Result<dynamic>>(
                this,
                Invocation.method(#deleteCurrentUser, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<dynamic>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i5.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i3.Stream<_i5.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i5.User?>.empty(),
          )
          as _i3.Stream<_i5.User?>);
}

/// A class which mocks [TaskRepoInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepoInterface extends _i1.Mock implements _i7.TaskRepoInterface {
  @override
  _i3.Stream<_i4.Result<List<_i8.Item>>> watchTasksByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasksByDate, [date]),
            returnValue: _i3.Stream<_i4.Result<List<_i8.Item>>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i4.Result<List<_i8.Item>>>.empty(),
          )
          as _i3.Stream<_i4.Result<List<_i8.Item>>>);
}
